Repository Interacao-Humano-Computador/2020.1-AliExpress, pull requests merged in 2020-09, with the labels that each got.

#14 #5 schedule page
  docs/_sidebar.md
  docs/index.html
  docs/pages/planning/planning.md
  docs/pages/planning/schedule/Images/schedule.png
  docs/pages/planning/schedule/schedule.md
Labels: Documentação, Média

#15 #10 design process page
  docs/_sidebar.md
  docs/pages/planning/designProcess/Images/ciclo.png
  docs/pages/planning/designProcess/designProcess.md
  docs/pages/planning/planning.md
Labels: Documentação, Média, Revisão

#16 Hot fixes img not showing drop down bug
  docs/_coverpage.md
  docs/_sidebar.md
  docs/pages/planning/designProcess/designProcess.md
Labels: Documentação, Média, bug

#20 [#19] Added the first presentation.
  docs/_sidebar.md
  docs/pages/presentations/presentations.md
Labels: Apresentação 1, Baixa, Documentação
