Repository Interacao-Humano-Computador/2020.1-AliExpress, pull requests merged in 2020-10, with the labels that each got.

#29 27 task analysis
  docs/_sidebar.md
  docs/pages/requirementsAnalysis/taskAnalysis/images/v0.2AT/BuyPath.svg
  docs/pages/requirementsAnalysis/taskAnalysis/images/v0.2AT/LoginPath.svg
  docs/pages/requirementsAnalysis/taskAnalysis/images/v0.2AT/SellPath.svg
  docs/pages/requirementsAnalysis/taskAnalysis/images/v1AT.jpeg
  docs/pages/requirementsAnalysis/taskAnalysis/taskAnalysis.md
Labels: Alta, Apresentação 2, Documentação

#39 Added the general principles document.
  README.md
  docs/README.md
  docs/_sidebar.md
  docs/pages/requirementsAnalysis/GeneralPrinciples/GeneralPrinciples.md
Labels: Apresentação 3, Documentação, Média

#41 Update GeneralPrinciples.md
  docs/pages/requirementsAnalysis/GeneralPrinciples/GeneralPrinciples.md
Labels: Alta, Apresentação 3, Documentação

#49 43 storyboard
  docs/_sidebar.md
  docs/pages/requirementsAnalysis/storyboard/images/fluxo-de-compras.png
  docs/pages/requirementsAnalysis/storyboard/images/fluxo-de-login.png
  docs/pages/requirementsAnalysis/storyboard/images/fluxo-de-vendas.png
  docs/pages/requirementsAnalysis/storyboard/storyboard.md
Labels: hacktoberfest-accepted

#50 48 pilot test
  docs/_sidebar.md
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/AvaliaçãodoTestePiloto.docx
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/AvaliaçãodoTestePiloto.pdf
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/TermodeConsentimento.pdf
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/barra_pesquisa.png
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/barra_pesquisa_evidencia.png
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/cadastro.png
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/comprar.png
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/eletronico1.png
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/eletronico2.png
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/login.png
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/maquiagem.png
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/persona1.jpeg
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/persona2.jpeg
  docs/pages/design_avaliation_development/pilotTestAvaliation/images/roupa.png
  docs/pages/design_avaliation_development/pilotTestAvaliation/pilotTestAvaliation.md
  docs/pages/design_avaliation_development/storyboard/images/fluxo-de-compras.png
  docs/pages/design_avaliation_development/storyboard/images/fluxo-de-login.png
  docs/pages/design_avaliation_development/storyboard/images/fluxo-de-vendas.png
  docs/pages/design_avaliation_development/storyboard/storyboard.md
  docs/pages/design_avaliation_development/taskAnalysisAvaliation/images/v0.3HTA/HTA-Comprar.png
  docs/pages/design_avaliation_development/taskAnalysisAvaliation/images/v0.3HTA/HTA-FluxodeLogin.png
  docs/pages/design_avaliation_development/taskAnalysisAvaliation/images/v0.3HTA/HTA-Vender.png
  docs/pages/design_avaliation_development/taskAnalysisAvaliation/taskAnalysisAvaliation.md
  docs/pages/requirementsAnalysis/GeneralPrinciples/GeneralPrinciples.md
  docs/pages/requirementsAnalysis/taskAnalysis/taskAnalysis.md
Labels: Apresentação 3, Documentação, Média, hacktoberfest-accepted
